export const TOGGLE_EDITION_PALETTE = 'TOGGLE_EDITION_PALETTE';
export const TOGGLE_GLOBAL_VIEW = 'TOGGLE_GLOBAL_VIEW';
export const TOGGLE_INSPECTOR = 'TOGGLE_INSPECTOR';
export const SELECT_TRACK = 'SELECT_TRACK';
export const SELECT_MEASURE = 'SELECT_MEASURE';
export const SELECT_DURATION = 'SELECT_DURATION';
export const SELECT_STRING = 'SELECT_STRING';
